language: node_js
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - nickjohnson.dev@gmail.com
node_js:
  - '8'
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run testonce
  - npm run trybuild
after_success:
  - npm run semantic-release
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
