language: node_js
notifications:
  email:
    recipients:
      - nickjohnson.dev@gmail.com
node_js: 8
before_script:
  - npm prune
script:
  - npm run lint
  - npm run testonce
  - npm run build
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
