export const ACTION_OCCURRED = 'ACTION_OCCURRED';
export const PLAYBACK_STATE_SET = 'PLAYBACK_STATE_SET';
export const POSITION_SET = 'POSITION_SET';
export const UPDATE_REQUESTED = 'UPDATE_REQUESTED';
